ShowcaseScreen:
    name: 'TradeBroadcast'
    BoxLayout:
        orientation: "vertical"
        size_hint_y: None
        height: 400
        canvas:
            Color:
                rgb: (.7, .7, .7)
            Rectangle:
                size: self.size
                pos: self.pos
        Label:
            text:'TradeBroadcast working on it'
            size_hint_y: None
            height: '30dp'
        
        
        Widget: